### PR TITLE
Updated ggez usage to reflect v0.5.0-rc.1

### PR DESCRIPTION
**Pull request by MCluck90**
This is in response to issue #10 

ggez v0.5.0 isn't stable yet and the devel branch seems to be broken right now which is why I'm pointing at master. I suspect it'd be preferred to wait for v0.5.0 to be stabilized before upgrading ggez-goodies but I wanted to get a start on it now haha. This doesn't bring in euclid or mint, it just makes sure that it compiles and the existing tests pass.

Is this the direction you were wanting to take it?

### CODE REVIEW

**Comment by icefoxen** [comment]
Seems pretty good, thank you!  I still claim I'm going to release 0.5.0-rc.1 Real Soon Now and then we can target that, but for now this is great.

**Comment by MCluck90** [comment]
Sounds good! I'll keep an eye out for 0.5.0-rc.1

**Comment by MCluck90** [comment]
I got it updated to where it uses v0.5.0-rc.1. A lot of the `Point2` and `Vector2` code has gotten a lot more verbose since mint doesn't implement any of the `std::ops` traits and Rust won't let us do the implementations for it. We could write some wrapper types for the mint types but I feel like that defeats the purpose of using mint.

If you've got some ideas for cleaning up that code then I'm all for it but otherwise, it's not the worst thing to have to write out each component of a vector when doing addition etc. I'm still updating the tests so I wouldn't call this merge-ready yet

**Comment by icefoxen** [comment]
For the purposes of ggez-goodies I feel fine just saying "we will use `nalgebra` 0.18" or whatever... so, pick a Real Math Library (which mint is not) and run with it.  I haven't checked out `nalgebra-glm` yet but it might be ideal.

**Comment by MCluck90** [comment]
Cool, I'll take care of it!

**Comment by icefoxen** [comment]
Looks good!  Ready for merge?

**Comment by MCluck90** [comment]
Ready on my end

**Pull request merged**
